# Generated by Django 5.2.4 on 2025-07-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('service_time', models.CharField(choices=[('now', 'Now'), ('later', 'Schedule for Later')], max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('loading_help', models.CharField(choices=[('self', 'I will load and unload the cargo myself'), ('need_help', 'I want help loading and unloading the cargo')], max_length=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_banking', 'Mobile Banking')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_item_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BigItemStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_location', models.CharField(max_length=255)),
                ('stop_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the stop')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bigiteam.bigitemservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
