# Generated by Django 5.2.4 on 2025-08-02 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpersService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_helpers', models.PositiveIntegerField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, help_text='Estimated duration in hours', max_digits=5)),
                ('offer_per_helper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.helpcategory')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpers_services', to='payments.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
