# Generated by Django 5.2.4 on 2025-08-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupDeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('car', 'Car')], max_length=10)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_phone_number', models.CharField(max_length=20)),
                ('pickup_description', models.TextField(help_text='What do you need to pickup?')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(max_length=255)),
                ('delivery_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_phone_number', models.CharField(max_length=20)),
                ('delivery_description', models.TextField(help_text='What do you need to deliver at this location?')),
                ('stop_order', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_stops', to='pickup_delivery.pickupdeliveryservice')),
            ],
        ),
    ]
