# Generated by Django 5.2.4 on 2025-07-30 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_category_icons/')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovingItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='moving.itemcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MovingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_address', models.CharField(max_length=255)),
                ('starting_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('select_date', models.DateField()),
                ('select_time', models.TimeField()),
                ('starting_floor_level', models.PositiveIntegerField()),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_floor_level', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_requests', to='moving.elevatoroption')),
                ('destination_location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_requests', to='moving.locationtype')),
                ('starting_elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_requests', to='moving.elevatoroption')),
                ('starting_location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_requests', to='moving.locationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_requests', to=settings.AUTH_USER_MODEL)),
                ('destination_parking_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_requests', to='moving.parkingtype')),
                ('starting_parking_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_requests', to='moving.parkingtype')),
            ],
        ),
        migrations.CreateModel(
            name='MovingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moving.movingitemoption')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_items', to='moving.movingrequest')),
            ],
        ),
    ]
