# Generated by Django 5.2.4 on 2025-07-31 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movingrequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movingrequest',
            name='upload_media',
            field=models.FileField(blank=True, null=True, upload_to='moving_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
